services:
  ollama:
    profiles: ['disabled']
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     OLLAMA_BASE_URL: '/ollama'
    #     NPM_REGISTRY: ${NPM_REGISTRY-}
    #     PIP_MIRROR: ${PIP_MIRROR-}
    #     APT_MIRROR: ${APT_MIRROR-}
    #     USE_SLIM: ${USE_SLIM-false}
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    depends_on:
      - postgres
    volumes:
      - open-webui:/app/backend/data
    #depends_on:
    #  - ollama
    #ports:
    #  - ${OPEN_WEBUI_PORT-3000}:8080
    networks:
      - default
      - web
    expose:
      - 8080
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/owu
      # OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_SECRET_KEY:
      # Qdrant
      VECTOR_DB: qdrant
      QDRANT_URI: http://qdrant:6333/
      # QDRANT_API_KEY:
      # Enable the usage of memmap(also known as on-disk) storage
      QDRANT_ON_DISK: 
      # QDRANT_PREFER_GRPC: false
      # QDRANT_GRPC_PORT: 6334
      # QDRANT_TIMEOUT: 5
      # QDRANT_HNSW_M: 16
      # ENABLE_QDRANT_MULTITENANCY_MODE: true
      # QDRANT_COLLECTION_PREFIX: open-webui
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    labels:
      caddy: owu.example.com
      caddy.reverse_proxy: "{{upstreams http 8080}}"

  postgres:
    image: postgres:${POSTGRES_VERSION}
    # command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      timeout: 10s
      retries: 5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./postgres.conf:/etc/postgresql/postgresql.conf
      - postgres:/var/lib/postgresql
    # ports:
    #   - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  qdrant:
    image: qdrant/qdrant:${QDRANT_VERSION}
    restart: unless-stopped
    container_name: owu-qdrant
    # ports:
    #  - 6333:6333
    #  - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  web:
    external: true

volumes:
  open-webui:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/data
      o: bind
  postgres:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/postgres
      o: bind
  qdrant_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/qdrant/data
      o: bind
  ollama:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/ollama
      o: bind
